### ISSUE TITLE
[Bug] connecting to neo4j

### ISSUE THREAD

**Issue by sonic182** [sagastume/boltx#99]
### Elixir and Erlang/OTP versions

For a neo4j in docker compose:

```yaml
services:
  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/12341234
    ports:
      - 7474:7474
      - 7687:7687
```

When I connect to neo4j without `uri` it works

![image](https://github.com/user-attachments/assets/f7f35bef-f599-4093-8139-ef3c76b6c578)

but when I use uri it doesn't

![image](https://github.com/user-attachments/assets/4adbc82d-a439-4510-9853-94244ca8e482)

### Operating system

Manjaro

### Neo4j version

5

### Boltx version

0.0.6

### Current behavior

I get abborted in livebook

### Expected behavior

to connect
